version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      base-image:
        dependency-type: "production"
    commit-message:
      prefix: "[base image] "
