---
name: PR Check

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: |
            python -m pip install --upgrade pipenv wheel

      - name: Install Openapi-spec-validator
        run: |
            pipenv install openapi-spec-validator
        
      - name: Run Openapi Validation
        run: |
            pipenv run openapi-spec-validator internal/api/openapi.json

